version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: t2_so1_db
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
  server:
    image: t2_so1_backend
    container_name: t2_so1_backend
    restart: always
    ports:
      - 9000:9000

  client:
    image: t2_so1_frontend
    container_name: t2_so1_frontend
    ports:
      - 3000:3000

volumes:
  mongodb_data: